const textStyles = {
  h1: {
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '32px',
    lineHeight: '38px',
    letterSpacing: '-0.01em',
  },
  h2: {
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '24px',
    lineHeight: '29px',
    letterSpacing: '-0.01em',
  },
  h3: {
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '18px',
    lineHeight: '22px',
    letterSpacing: '-0.01em',
  },
  body1: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '100%',
    letterSpacing: '-0.01em',
  },
  multiBody1: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '150%',
    letterSpacing: '-0.01em',
  },
  body2: {
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '100%',
    letterSpacing: '-0.01em',
  },
  multiBody2: {
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '150%',
    letterSpacing: '-0.01em',
  },
  body3: {
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '13px',
    lineHeight: '100%',
    letterSpacing: '-0.01em',
  },
  multiBody3: {
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '13px',
    lineHeight: '150%',
    letterSpacing: '-0.01em',
  },
  caption: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '100%',
    letterSpacing: '-0.01em',
  },
  multiCaption: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '150%',
    letterSpacing: '-0.01em',
  },
  buttonMedium: {
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '100%',
    letterSpacing: '-0.01em',
    color: '#FF6F1E',
  },
  buttonSmall: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '100%',
    letterSpacing: '-0.01em',
    color: '#FF6F1E',
  },
};

export default textStyles;
